name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: jcs090218
  REPO: jcs-emacs

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs-version: [27.x, 28.x, 29.x, 30.x, snapshot]

    steps:
    - uses: actions/checkout@v4

    - name: Build image
      run: |
        docker build --no-cache -t ${{ env.REGISTRY }}/${{ env.REPO }} ./${{ matrix.emacs-version }}/
